### ISSUE TITLE
Fatal error: Line 1: Unexpected reserved word

### ISSUE THREAD

**Issue by padsbanger** [justinjmoses/caseify#5]
Hello, I am trying to use plugin like this in my Gruntfile:

```
    browserify: {
      dist: {
        options: {
          transform: [
            ['babelify', {
              presets: ['es2015', 'react']
            }], ['caseify']
          ],
          watch: true
        },
        files: {
          './dist/app.js': ['./src/js/app.js']
        }
      }
    },
```

However when I try to compile I get following error in console:

`Fatal error: Line 1: Unexpected reserved word`

**Comment by iafiawik** [comment]
@padsbanger Did you find a solution to this? I am facing the same error.

**Comment by padsbanger** [comment]
@iafiawik I have ended up not using this at all, just trying to be careful :)

**Comment by iafiawik** [comment]
@padsbanger Thanks for the update!
